---
deployment:
  tasks:
    - export DEPLOYPATH=/home/vremens2/public_html/
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R svg $DEPLOYPATH
    - /bin/cp -R index.html $DEPLOYPATH
    - /bin/cp -R script.js $DEPLOYPATH
    - /bin/cp -R style.css $DEPLOYPATH